openapi: 3.0.0
info:
  title: hhplus-ecommerce-server API
  version: 1.0.0

tags:
  - name: users
  - name: products
  - name: orders

paths:
  /users/{userId}/balances:
    get:
      tags:
        - users
      summary: 잔액 조회
      description: 유저ID에 해당하는 현재 잔액을 조회합니다.
      parameters:
        - name: userId
          in: path
          required: true
          description: 유저ID
          schema:
            type: integer
      responses:
        '200':
          description: 잔액 조회 성공
          content:
            application/json:
              example:
                userId: 1
                balance: 1000
        '400':
          description: 잘못된 요청(음수 유저ID)
        '404':
          description: 사용자를 찾을 수 없음
    patch:
      tags:
        - users
      summary: 잔액 충전
      description: 유저ID에 요청한 금액만큼 잔액을 충전합니다.
      parameters:
        - name: userId
          in: path
          required: true
          description: 유저ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: integer
                  description: 충전할 금액
              required:
                - amount
            example:
              amount: 1000
      responses:
        '200':
          description: 잔액 충전 성공
          content:
            application/json:
              example:
                userId: 1
                balance: 2000
        '400':
          description: 잘못된 요청(음수 금액, 최대 잔고 초과)
        '404':
          description: 사용자를 찾을 수 없음

  /users/{userId}/coupons:
    post:
      tags:
        - users
      summary: 쿠폰 발급
      description: 쿠폰을 요청한 유저ID에 발급합니다.
      parameters:
        - name: userId
          in: path
          required: true
          description: 유저ID
          schema:
            type: integer
      responses:
        '200':
          description: 쿠폰 발급 성공
          content:
            application/json:
              example:
                couponId: 10
                discountRate: 20
        '400':
          description: 잘못된 요청(음수 유저ID)
        '404':
          description: 쿠폰을 찾을 수 없음


  /products/{productId}:
    get:
      tags:
        - products
      summary: 상품 조회
      description: 상품ID에 해당하는 상품을 조회합니다.
      parameters:
        - name: productId
          in: path
          required: true
          description: 상품ID
          schema:
            type: integer
      responses:
        '200':
          description: 상품 조회 성공
          content:
            application/json:
              example:
                productId: 1
                quantity: 5
        '400':
          description: 잘못된 요청(음수 상품ID)
        '404':
          description: 상품을 찾을 수 없음

  /products/top-selling:
    get:
      tags:
        - products
      summary: 베스트 상품 조회
      description: 최근 3일간 가장 많이 팔린 상위 5개 상품 조회
      responses:
        '200':
          description: 베스트 상품 조회 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    productId:
                      type: integer
                      description: 상품 ID
                    quantity:
                      type: integer
                      description: 판매 수량
              example:
                - productId: 1
                  quantity: 12
                - productId: 2
                  quantity: 9
                - productId: 3
                  quantity: 8
                - productId: 4
                  quantity: 6
                - productId: 5
                  quantity: 4
        '404':
          description: 데이터 부족으로 베스트 상품을 찾을 수 없음

  /orders/{userId}:
    post:
      tags:
        - orders
      summary: 주문 및 결제
      description: 유저가 요청한 상품 리스트를 쿠폰과 함께 주문 및 결제합니다.
      parameters:
        - name: userId
          in: path
          required: true
          description: 유저ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                couponId:
                  type: integer
                  description: 적용할 쿠폰 ID (선택)
                  nullable: true
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: integer
                        description: 상품 ID
                      quantity:
                        type: integer
                        description: 구매 수량
                  minItems: 1
              required:
                - items
            example:
              couponId: 10
              items:
                - productId: 1
                  quantity: 2
                - productId: 2
                  quantity: 3
                - productId: 3
                  quantity: 2
      responses:
        '200':
          description: 주문 및 결제 성공
          content:
            application/json:
              example:
                orderId: 2
                totalPrice: 20000
                discountRate: 5
                paidPrice: 19000
        '400':
          description: 잘못된 요청(음수 유저ID, 잔고 부족, 상품 재고 초과, 만료된 쿠폰)
        '404':
          description: 사용자 혹은 상품을 찾을 수 없음